<section id="books-destaque" class="container-content">
	<div class="content">
		<h1 class="title-content text-left">Livros em Destaque</h1>	
		<div class="container-fluid">

			<div class="row">
				<?php
					if (count($this->view->booksDestaque) > 0) {
						$this->view->renderBook->__set('books', $this->view->booksDestaque);
						$this->view->renderBook->createBooks();
					} else { 
				?>
					<h4 class="not-books">Não há livros para mostrar</h4>
				<?php } ?>
			</div>

		</div>
	</div>
</section>

<section id="books-novos" class="bg-white">
	<div class="content" id="card-dark">
		<h1 class="title-content">Novos Livros</h1>	
		<div class="container-fluid">
			<?php 
				$validNewBooks = count($this->view->newBooks) > 0;
			?>

			<div class="row">
				<?php
					if ($validNewBooks) {
						$this->view->renderBook->__set('books', $this->view->newBooks);
						$this->view->renderBook->createBooks();
					} else {
				?>
				<h4 class="not-books">Não há novos livros para mostrar</h4>
				<?php } ?>
			</div>

			<?php if ($validNewBooks) { ?>
				<div class="container-button-books">
					<a href="/livros" class="btn btn-dark ml-auto">Veja Mais</a>
				</div>
			<?php } ?>			

		</div>
	</div>
</section>

<section id="autores-books">
	<div class="content">

		<?php 
			$validAutores = count($this->view->autores) > 0;
			$count = count($this->view->autores) > 4;
		?>

		<h1 class="title-content">Autores Favoritos</h1>	

		<?php if ($validAutores) { ?>
			<div id="slideAutores" class="carousel slide carousel-fade" data-ride="carousel">
				<ol class="carousel-indicators">
					<li data-target="#slideAutores" data-slide-to="0" class="active"></li>
					<?php if ($count) { ?>
						<li data-target="#slideAutores" data-slide-to="1"></li>
					<?php } ?>
				</ol>

				<div class="carousel-inner">
					<div class="carousel-item active">
						<div class="container-fluid">
							<div class="row">
								<?php 
									$this->view->renderAutores->__set('autores', $this->view->autoresDestaque);
									$this->view->renderAutores->createAutor(4, 0);
								?>
							</div>
						</div>
					</div>


					<?php if (count($this->view->autores) > 4) { ?>
						<div class="carousel-item">
							<div class="container-fluid">
								<div class="row">
									<?php $this->view->renderAutores->createAutor(8, 4); ?>
								</div>

							</div>
						</div>
					<?php } ?>
				</div>

				<?php if ($count) { ?>
					<a class="carousel-control-prev" href="#slideAutores" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Anterior</span>
					</a>
				<?php } ?>
				
				<?php if ($count) { ?>
					<a class="carousel-control-next" href="#slideAutores" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Próximo</span>
					</a>
				<?php } ?>
				
			</div>
		<?php } else { ?>
			<h4 class="not-books">Não há autores para mostrar</h4>
		<?php } ?>

	</div>
</section>