<section>
	<div class="content">
		<div class="box">
			<div class="container-fluid">
				<div class="row">
					<?php
						if (count($this->view->books) > 0) { ?>
							<h3 class="title-content col-12">Meus Livros</h3>
						<?php
							$this->view->renderBook->__set('books', $this->view->books);
							$this->view->renderBook->createBooks(false);
						} else {
					?>
					<h4 class="not-books">Você não comprou livros ainda</h4>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</section>