<html lang="pt-br">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta charset="utf-8">

		<!-- Bootstrap Css -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

		<!-- Font Awesome -->
		<link rel="stylesheet" href="/fontawesome/css/all.css">

		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css2?family=Secular+One&display=swap" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css2?family=Sansita+Swashed&display=swap" rel="stylesheet"> 

		<!-- Estilo Css -->
		<link rel="stylesheet" href="/css/dashboard.css">

		<?php 
			if (isset($this->view->css)) {
				foreach ($this->view->css as $indice => $estilo) {
					echo "<link rel='stylesheet' type='text/css' href='/css/". $estilo .".css'>";
				}
			}
		?>

		<link rel="stylesheet" href="/css/dashboard-media-query.css">
		<link rel="stylesheet" href="/css/animation.css">
		

		<?php 
			$title = isset($this->view->title) ? $this->view->title : 'Login Administrativo';
		?>
		<title>LoveBook - <?= $title ?></title>
		<link rel="icon" href="/imagens/favicon.png">

		<!-- Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	</head>
	<body>

		<section>
			<div class="content">
				
				<div id="menu-dashboard">
					<h1 class="title-dashboard">Dashboard</h1>

					<div id="hamburguer">
						<button>
							<i class="fas fa-bars"></i>
						</button>
					</div>

					<ul class="list-itens-dashboard">

						<li data-id="5" class="itens-list-dashboard">
							<span class="item-dashboard">

								<div class="collection-dashboard w-100">
									<i class="fas fa-home icon-collection-item"></i>
									<a href="/dashboard" class="title-collection-item w-100 loggout">Dashboard</a>
								</div>
							</span>
						</li>

						<li data-id="0" class="itens-list-dashboard">
							<span class="item-dashboard">
								
								<div class="collection-dashboard">
									<i class="fas fa-book icon-collection-item"></i>
									<h4 class="title-collection-item">Livros</h4>
								</div>
								<i class="fas fa-caret-right"></i>
							</span>

							<div class="item-list-desc">
								<ul class="list-links-dashboard">
									<li>
										<a href="/dashboard/lista_livros" class="links-dashboard">
											Livros
										</a>
									</li>

									<li>
										<a href="/dashboard/publicar_livro" class="links-dashboard">
											Publicar livro
										</a>
									</li>

									<li>
										<a href="/dashboard/editar_livro" class="links-dashboard">
											Editar livro
										</a>
									</li>

									<li>
										<a href="/dashboard/remover_livro" class="links-dashboard">
											Remover livro
										</a>
									</li>
								</ul>
							</div>
						</li>

						<li data-id="1" class="itens-list-dashboard">
							<span class="item-dashboard">
								
								<div class="collection-dashboard">
									<i class="fas fa-users icon-collection-item"></i>
									<h4 class="title-collection-item">Autores</h4>
								</div>
								<i class="fas fa-caret-right"></i>
							</span>

							<div class="item-list-desc">
								<ul class="list-links-dashboard">
									<li>
										<a href="/dashboard/lista_autores" class="links-dashboard">
											Autores
										</a>
									</li>

									<li>
										<a href="/dashboard/criar_autor" class="links-dashboard">
											Criar novo autor
										</a>
									</li>

									<li>
										<a href="/dashboard/editar_autor" class="links-dashboard">
											Editar autor
										</a>
									</li>

									<li>
										<a href="/dashboard/remover_autor" class="links-dashboard">
											Remover autor
										</a>
									</li>
								</ul>
							</div>
						</li>

						<li data-id="2" class="itens-list-dashboard">
							<span class="item-dashboard">
								
								<div class="collection-dashboard">
									<i class="fas fa-user-tie icon-collection-item"></i>
									<h4 class="title-collection-item">Administradores</h4>
								</div>
								<i class="fas fa-caret-right"></i>
							</span>

							<div class="item-list-desc">
								<ul class="list-links-dashboard">
									<li>
										<a href="/dashboard/lista_administradores" class="links-dashboard">
											Administradores
										</a>
									</li>

									<li>
										<a href="/dashboard/criar_administrador" class="links-dashboard">
											Criar administrador
										</a>
									</li>

									<li>
										<a href="/dashboard/remover_administrador" class="links-dashboard">
											Remover administrador
										</a>
									</li>
								</ul>
							</div>
						</li>

						<li data-id="3" class="itens-list-dashboard">
							<span class="item-dashboard">
								
								<div class="collection-dashboard">
									<i class="fas fa-user-cog icon-collection-item"></i>
									<h4 class="title-collection-item">Minha Conta</h4>
								</div>
								<i class="fas fa-caret-right"></i>
							</span>

							<div class="item-list-desc">
								<ul class="list-links-dashboard">
									<li>
										<a href="/dashboard/editar_conta" class="links-dashboard">
											Editar Conta
										</a>
									</li>
								</ul>
							</div>
						</li>

						<li data-id="4" class="itens-list-dashboard">
							<span class="item-dashboard">

								<div class="collection-dashboard w-100">
									<i class="fas fa-sign-out-alt icon-collection-item"></i>
									<a href="/loggout_adm" class="title-collection-item w-100 loggout">Deslogar</a>
								</div>
							</span>
						</li>

						<li data-id="6" class="itens-list-dashboard">
							<span class="item-dashboard">

								<div class="collection-dashboard w-100">
									<i class="fas fa-backward icon-collection-item"></i>
									<a href="/" class="title-collection-item w-100 loggout">Voltar ao Site</a>
								</div>
							</span>
						</li>
					</ul>
				</div>

				<div id="main">
					<div class="caminho">
						<ul>
							<li>
								<a href="/dashboard"><i class="fas fa-home mr-1"></i> Dashboard</a>
							</li>

							<?php 
								$url = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
								$exUrl = explode('/', $url);
								unset($exUrl[0]);
								unset($exUrl[1]);


								foreach ($exUrl as $item) {
									$name = ucfirst(str_replace('_', ' ', $item));
							?>

							<li>
								<a href="/dashboard/<?= $item ?>"><?= $name ?></a>
							</li>

							<?php } ?>
						</ul>
					</div>

					<?php $this->content() ?>

					<?php
					if (isset($_SESSION['adm']['notification'])) { ?>
						<div class="notificationDashboard">				
							<h3 class="notificationTitle"><?= $_SESSION['adm']['notification']['msg'] ?></h3>
						</div>	
						<?php 
						unset($_SESSION['adm']['notification']);
					} 
					?>
				</div>



			</div>
		</section>
	
		<!-- Script JS -->
		<script src='/js/dashboard.js'></script>
		<?php
			if (isset($this->view->js)) {
				foreach ($this->view->js as $indice => $script) {
					echo "<script src='/js/". $script .".js'></script>";
				}
			}
		?>

	</body>
</html>