<?php session_start(); ?>

<html lang="pt-br">
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta charset="utf-8">

		<!-- Bootstrap Css -->
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

		<!-- Font Awesome -->
		<link rel="stylesheet" href="/fontawesome/css/all.css">

		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Libre+Baskerville:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet"> 
		<link href="https://fonts.googleapis.com/css2?family=Secular+One&display=swap" rel="stylesheet"> 

		<!-- Estilo Css -->

		<?php 
			if (isset($this->view->css)) {
				foreach ($this->view->css as $indice => $estilo) {
					echo "<link rel='stylesheet' type='text/css' href='/css/". $estilo .".css'>";
				}
			}
		?>		

		<?php 
			$title = isset($this->view->title) ? $this->view->title : 'Login Administrativo';
		?>
		<title>LoveBook - <?= $title ?></title>
		<link rel="icon" href="/imagens/favicon.png">

		<!-- Bootstrap JS -->
		<script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

	</head>
	<body>
		<?php $this->content() ?>

		<?php
		if (isset($_SESSION['auth']['notification'])) { ?>
			<div class="notificationDashboard">				
				<h3 class="notificationTitle"><?= $_SESSION['auth']['notification']['msg'] ?></h3>
			</div>	
			<?php 
			unset($_SESSION['auth']['notification']);
		} 
		?>
	
		<!-- Script JS -->
		<?php
			if (isset($this->view->js)) {
				foreach ($this->view->js as $indice => $script) {
					echo "<script src='/js/". $script .".js'></script>";
				}
			}
		?>

	</body>
</html>