<div class="container-fluid">
	<div class="row">
		<div class="conteudo col-12">
			<div class="conteudo-header">
				<h2 class="conteudo-title">Editar informações do autor - Selecione o autor</h2>
			</div>

			<div class="conteudo-body">
				<div id="card-dark" class="container">
					<div class="row">
						<?php 
							$this->view->renderAutores->__set('autores', $this->view->autores);
							$this->view->renderAutores->createAutor(16, 0);
						?>
					</div>
				</div>
				
			</div>		
		</div>
	</div>
</div>