<div class="container-fluid">
	<div class="row">
		<div class="conteudo col-12">
			<div class="conteudo-header">
				<h2 class="conteudo-title">Editar Livros - Selecione o livro</h2>
			</div>

			<div class="conteudo-body">
				<div id="card-dark" class="container">
					<div class="row">
						<?php 
							$this->view->renderBook->__set('books', $this->view->newBooks);
							$this->view->renderBook->createBooks(false);
						?>
					</div>
				</div>
				
			</div>		
		</div>
	</div>
</div>	