<div class="container-fluid">
	<?php 

		$senha = base64_decode($this->view->adm['senha']);
		$count_senha = '';
		for ($i = 0; $i < strlen($senha); $i++) { $count_senha .= '*';}

		$usuario = str_replace('#', '', $this->view->adm['usuario']);
 	?>
	<div class="row">
		<div class="conteudo col-12">
			<div class="conteudo-header">
				<h2 class="conteudo-title">Editar Conta</h2>
			</div>

			<div class="conteudo-body">
				
				<form action="/dashboard/editAccountAdm" method="POST">
					<div class="form-row">
						<div class="form-group col-5">
							<label for="nome">Nome</label>
							<input type="text" autocomplete="off" class="form-control" id="nome" name="nome" placeholder="Digite o nome do administrador" value="<?= $this->view->adm['nome'] ?>" required="">
							<span class="help-digit"></span>
						</div>

						<div class="form-group col-4">
							<label for="sobrenome">Sobrenome</label>
							<input type="text" class="form-control" id="sobrenome" name="sobrenome" placeholder="Digite o sobrenome do administrador" value="<?= $this->view->adm['sobrenome'] ?>">
						</div>

						<div class="form-group col-md-3">
							<label for="usuario">Usuário</label>
							<div class="input-group mb-2 mr-sm-2">
								<div class="input-group-prepend">
									<div class="input-group-text">#</div>
								</div>
								<input type="text" class="form-control" id="usuario" name="usuario" placeholder="Digite um usuário" autocomplete="off" required="" value="<?= $usuario ?>">
							</div>
							<span class="help-digit"></span>
						</div>
					</div>

					<div class="form-row">
						<div class="form-group col-4">
							<label for="email">Email</label>
							<input type="email" class="form-control" id="email" name="email" placeholder="Digite o email do administrador" required="" value="<?= $this->view->adm['email'] ?>">
							<span class="help-digit"></span>
						</div>

						<div class="form-group col-md-5">
							<label for="senha">Senha</label>
							<input type="password" class="form-control" id="senha" name="senha" required="" placeholder="<?= $count_senha ?>" >
							<span class="help-digit"></span>
						</div>

						<div class="form-group col-md-3">
							<label for="confirmSenha">Senha novamente</label>
							<input type="password" class="form-control" id="confirmSenha" name="confirmSenha" required="" placeholder="Digite sua senha novamente">
							<span class="help-digit"></span>
						</div>
						
						
					</div>

					<button type="submit" class="btn btn-primary d-block ml-auto">Editar Conta</button>
				</form>
			</div>		
		</div>
	</div>
</div>	