<div class="container-fluid">
	<div class="row">
		<div class="conteudo col-12">
			<div class="conteudo-header">
				<h2 class="conteudo-title">Publicar Livro</h2>
				<span class="for-itens-full">* Obrigatórios</span>
			</div>

			<div class="conteudo-body">
				<?php 
					if(count($this->view->autores) <= 0) { ?>
						<h4 class="text-center" style="font-size: 0.7em;">* Você deve criar um autor primerio</h4>
					<?php } 
				?>

				<form action="/dashboard/public_book_adm" method="POST" enctype="multipart/form-data">
					<div class="form-row">
						<div class="form-group col" id="content-title">
							<label for="titulo">Título *</label>
							<input type="text" class="form-control" autocomplete="off" id="titulo" name="titulo" placeholder="Digite o título do livro" required="">
							<span class="help-digit"></span>
						</div>

						<div class="form-group col-md-auto" id="content-img">
							<label for="image" class="label-img">
								<i class="fas fa-image"></i>
								<input type="file" class="form-control d-none" accept="image/png, image/jpg, image/jpeg" id="image" name="image"> 
								<span id="result">
									<i class="fas fa-check text-warning"></i>
									<span class="title-img"></span>
								</span>
								<span class="help-digit"></span>
							</label>							
						</div>
					</div>

					<div class="form-row">
						<div class="form-group col-md-5" id="list-autores">
							<label for="autor">Autor *</label>
							<select id="autor" name="autor" class="form-control" required="">
								<option selected disabled>Escolher...</option>
								<?php foreach ($this->view->autores as $autor) { ?>
									<option value="<?= $autor['id'] ?>">
										<?= $autor['nome'] ?>	
									</option>
								<?php } ?>
							</select>
						</div>

						<div class="form-group col-md-4" id="content-data-lancamento">
							<label for="data_lancamento">Data de Lançamento *</label>
							<input type="date" class="form-control" id="data_lancamento" name="data_lancamento" required="">
							<span class="help-digit"></span>
						</div>			

						<div class="form-group col-md-3" id="content-preco">
							<label for="preco">Preço *</label>
							<div class="input-group mb-2 mr-sm-2">
								<div class="input-group-prepend">
									<div class="input-group-text">R$</div>
								</div>
								<input type="number" autocomplete="off" class="form-control" id="preco" name="preco" placeholder="Digite o preço que será vendido o livro" required="">
							</div>
							<span class="help-digit"></span>
						</div>			
					</div>

					<div class="form-row">
						<div class="form-group col-md-4" id="content-paginas">
							<label for="paginas">Páginas *</label>
							<input type="number" class="form-control" id="paginas" name="paginas" placeholder="Número de páginas do livro" required="">
							<span class="help-digit"></span>	
						</div>
					</div>

					<div class="form-row">
						<div class="form-group col" id="content-desc">
					    	<label for="desc">Descrição *</label>
					    	<textarea class="form-control w-100" id="desc" name="desc" rows="4" placeholder="Digite informações sobre o livro"></textarea>
							<span class="help-digit"></span>
					  	</div>				
					</div>				

					<button type="submit" class="btn btn-primary" id="send">Publicar Livro</button>
				</form>
			</div>		
		</div>
	</div>
</div>	