<div class="container-fluid">
	<div class="row">
		<div class="conteudo col-12">
			<div class="conteudo-header">
				<h2 class="conteudo-title">Remover autor - Selecione o autor</h2>
			</div>

			<div class="conteudo-body">
				<div id="card-dark" class="container">
					<div class="row">
						<?php 
							$this->view->renderAutores->__set('autores', $this->view->autores);
							$this->view->renderAutores->createAutor(16, 0);
						?>
					</div>
				</div>
				
			</div>		
		</div>
	</div>
</div>

<div id="confirmacao">
	<div class="confirm">
		<div class="box-confirm">
			<h1 class="title-confirm">Realmente deseja remover esse autor?</h1>
			<p class="desc-confirm">Todos os livros associados a ele também serão removidos</p>
			<div class="buttons-confirm">
				<button type="button" class="btn btn-danger cancel">
					Não
				</button>
				<button type="button" class="btn btn-primary send" data-id="">
					Sim
				</button>
			</div>
		</div>
	</div>
</div>