<div class="container-fluid">
	<div class="row">
		<div class="conteudo col-12">
			<div class="conteudo-header">
				<h2 class="conteudo-title">Remover Administrador - Selecione o administrador</h2>
			</div>

			<div class="conteudo-body">
				<?php 
					$this->view->renderAdm->__set('adminitradores', $this->view->adm);
					$this->view->renderAdm->renderAdm();
				?>				
			</div>		
		</div>
	</div>
</div>

<div id="confirmacao">
	<div class="confirm">
		<div class="box-confirm">
			<h1 class="title-confirm">Realmente deseja remover esse administrador?</h1>
			<div class="buttons-confirm">
				<button type="button" class="btn btn-danger cancel">
					Não
				</button>
				<button type="button" class="btn btn-primary send" data-id="">
					Sim
				</button>
			</div>
		</div>
	</div>
</div>