<div class="content">
	
	<div id="global">

		<div id="caixa-content">
			<div id="cabecalho">
				<h1 class="title">Login Administrativo</h1>				
			</div>

			<form action="/login_adminitrador" method="POST" id="main">
				<div class="form-row align-items-center">
					<div class="col-12">
						<label for="usuario">Email ou usuário:</label>
						<div class="input-group mb-2">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<i class="fas fa-user"></i>
								</div>
							</div>
							<input type="text" class="form-control" id="usuario" name="usuario" placeholder="Digite seu usuário ou email">
						</div>
					</div>
					<div class="col-12">
						<label for="senha">Senha:</label>
						<div class="input-group mb-2">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<i class="fas fa-lock"></i>
								</div>
							</div>
							<input type="password" class="form-control" id="senha" name="senha" placeholder="Digite sua senha">
						</div>
					</div>
					<div class="col">
						<button type="submit" class="send btn btn-dark">Logar</button>
					</div>
				</div>
				
			</form>
		</div>
	</div>
</div>