<?php session_start(); ?>
<div class="content">
	<div id="global">

		<div class="box">
			<form action="/logarUserAccount" method="POST" id="main">
				<h1 class="title-content mb-4">Login</h1>

				<div class="form-row align-items-center">
					<div class="col-12">
						<label for="usuario">Email, Usuário ou Cpf:</label>
						<div class="input-group mb-2">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<i class="fas fa-user"></i>
								</div>
							</div>
							<input type="text" class="form-control" id="usuario" name="usuario" placeholder="Digite seu usuário, email, ou cpf">
						</div>
					</div>
					<div class="col-12">
						<label for="senha">Senha:</label>
						<div class="input-group mb-2">
							<div class="input-group-prepend">
								<div class="input-group-text">
									<i class="fas fa-lock"></i>
								</div>
							</div>
							<input type="password" class="form-control" id="senha" name="senha" placeholder="Digite sua senha">
						</div>
					</div>
					<div class="col">
						<button type="submit" class="send btn btn-dark">Logar</button>
					</div>
				</div>

			</form>
		</div>

		<?php
			if (
					isset($_SESSION['lovebook']['auth']) && 
					isset($_SESSION['lovebook']['auth']['status']) && 
					$_SESSION['lovebook']['auth']['status'] == false
				) {
		?>
			<div class="box-notification">
				
				<h1 class="text-notification">
					<?php 
						$text = 'Login inválido!';
						echo $text;
						unset($_SESSION['lovebook']['auth']);
					?>

				</h1>
			</div>
		<?php } ?>

	</div>
</div>